- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: ADJUST HOSTNAME
      cisco.nso.nso_config:
        url: http://192.168.1.23::8080/jsonrpc
        username: admin
        password: admin
        data:
          tailf-ncs:devices:
          device:
          - name: asr1
            config:
              tailf-ned-cisco-ios-xr:hostname: "asr01"
